version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_kerootica
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - DB_HOST=host.docker.internal