"""cria tabela usuarios

Revision ID: 2663f496b860
Revises: eb79e20b05a8
Create Date: 2026-08-28 16:05:00.750023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2663f496b860'
down_revision = 'eb79e20b05a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email_login', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('admin', 'funcionario', name='perfil_usuario'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_login')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone2', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nome_mae', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('nome_pai', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('referencia', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=150), nullable=True))
        batch_op.alter_column('nome_completo',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('telefone1',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('telefone1',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('nome_completo',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('endereco')
        batch_op.drop_column('email')
        batch_op.drop_column('referencia')
        batch_op.drop_column('nome_pai')
        batch_op.drop_column('nome_mae')
        batch_op.drop_column('telefone2')

    op.drop_table('usuarios')
    # ### end Alembic commands ###
